// Interface
export const INCREMENT_INTERFACE_VALUE_TYPE = 'INCREMENT_INTERFACE_VALUE'
export const RESET_INTERFACE_VALUE_TYPE = 'RESET_INTERFACE_VALUE'
export const SET_INTERFACE_VALUES = 'SET_INTERFACE_VALUES'

// Settings
export const SET_SETTINGS_MAX_VALUE_TYPE = 'SET_SETTINGS_MAX_VALUE'
export const SET_SETTINGS_MIN_VALUE_TYPE = 'SET_SETTINGS_MIN_VALUE'

// Page
export const SET_COUNTING_MODE_TYPE = 'SET_COUNTING_MODE'
export const SET_ERROR_TYPE = 'SET_ERROR'